<nav>
    <a href="/" class="logo">
      <h2>HOF</h2> <span>band</span>
    </a>
    <div class="toggle" onClick="toggleMenu();"></div>
    <ul class="menu">
      <li><a href="#banner" onClick="toggleMenu();">Início</a></li>
      <li><a href="#aplicacoes" onClick="toggleMenu();">Aplicações</a></li>
      <li><a href="#caracteristicas" onClick="toggleMenu();">Características</a></li>
      <li><a href="#contato" onClick="toggleMenu();">Contato</a></li>
      <li><a href="#pedir" class="nav-comprar" onClick="toggleMenu();">Comprar</a></li>
    </ul>
  </nav>
  <section id="banner" class="banner">
    <div class="textBx">
      <h2>Faixa Compressiva <br><span>HOF </span> <span class="banner-band">band</span></h2>
      <h3>O mais importante é trazer conforto e benefício no pós-operatório de suas cirurgias</h3>
      <a href="#pedir" class="btn">Comprar</a>
    </div>
  </section>
  <section id="aplicacoes">
    <div class="heading">
      <h2>Aplicações</h2>
    </div>
    <div class="content">
      <div class="w50">
        <img src="/img/model-bichectomia.jpg" alt="Bichectomia">
      </div>
      <div class="contentBx w50 d-left">
        <h3>Bichectomia</h3>
        <p>
          Bichectomia (Lipoplastia Facial) é um procedimento cirúrgico para a remoção parcial ou total das bolas de
          Bichat,
          estruturas gordurosas da face. Por ser um procedimento cirúrgico pode ocorrer edema e hematomas. A faixa
          compressiva
          HOF band, ameniza a hemorragia e o edema, permitindo uma recuperação mais eficaz. A compressão minimiza o
          espaço
          morto que fica após a remoção da bola de Bichat.
        </p>
      </div>
    </div>
    <div class="content">
      <div class="w50 d-left">
        <img src="/img/model-lipopapada.jpg" alt="Lipo de Papada">
      </div>
      <div class="contentBx w50">
        <h3>Lipo de papada</h3>
        <p>
          Lipo de Papada (Redução de gordura submentoniana) é realizada através de aplicação de Ácido Deoxicólico ou com
          técnica aspirativa. A aplicação de ácido é feita com a
          utilização de agulha na região da papada. O ácido trabalha dissolvendo a gordura e deixando um espaço. A
          técnica aspirativa (Lipoaspiração) utiliza clânulas que aspiram o tecido gorduroso. Em ambas a utilização da
          faixa
          compressiva auxilia reduzindo os hematomas no local e modelando a face no pós-tratamento.
        </p>
      </div>
    </div>
    <div class="content">
      <div class="w50">
        <img src="/img/model-cirurgia.jpg" alt="Cirurgia">
      </div>
      <div class="contentBx w50 d-left">
        <h3>Cirurgia Oral</h3>
        <p>
          Muitas vezes após um cirurgia bucal é recomendado a aplicação de gelo no local, a faixa compressiva auxilia o
          possicionamento da bolsa de gelo no local apropriado.
        </p>
      </div>
    </div>
  </section>
  <section class="caracteristicas" id="caracteristicas">
    <div class="heading white">
      <h2>Características</h2>
      <p>Faixa compressiva universal de material confortável e ajustável.</p>
    </div>
    <div class="content">
      <div class="servicesBx">
        <img src="img/icon-band.png" />
        <h2>Faixa Compressiva</h2>
        <p>Faixa compressiva de tamanho único feita de material confortável, lavável e com ajustes para um encaixe mais
          anatômico</p>
      </div>
      <div class="servicesBx">
        <img src="img/icon-gelo.png" />
        <h2>Gelo Anatômico</h2>
        <p>Gelo em formato especial que se adapta as curvas do rosto e exerce uma compressão adequada. Ainda mantém a
          temperatura pelo tempo adequado no contato ao rosto.</p>
      </div>
      <div class="servicesBx">
        <img src="img/icon-necessaire.png" />
        <h2>Necessaire</h2>
        <p>Acompanha uma linda necessaire para guardar a faixa e o gelo durante o seu tempo de descanço, ainda pode ser
          utilizada futuramente para outros fins.</p>
      </div>
      <div class="servicesBx">
        <img src="img/icon-velcro.png" />
        <h2>Ajustável</h2>
        <p>Ajusta-se a maioria dos formatos de cabeça, podendo ainda ser utilizada em outras regiões do corpo.</p>
      </div>
    </div>
    </div>
  </section>

  <section class="contato" id="contato">
    <div class="heading white">
      <h2>Contato</h2>
      <p>Pretende comprar várias faixas para repassar para os seus pacientes, entre em contato conosco para saber dos
        valores especiais.</p>
    </div>
    <div class="content">
      <div class="contactInfo">
        <h3>Entre em contato</h3>
        <div class="contactInfoBx">
          <div class="box">
            <div class="icon"><i class="fa fa-phone"></i></div>
            <div class="text">
              <h3>Whatsapp</h3>
              <p><a href="https://api.whatsapp.com/send?1=pt_br&phone=+5561982827471">(61) 98282-7471</a></p>
            </div>
          </div>
          <div class="box">
            <div class="icon"><i class="fa fa-envelope-o"></i></div>
            <div class="text">
              <h3>E-mail</h3>
              <p><a href="mailto://contato@hofband.com.br">contato@hofband.com.br</a></p>
            </div>
          </div>
          <div class="box">
            <div class="icon"><i class="fa fa-map-marker"></i></div>
            <div class="text">
              <h3>Endereço</h3>
              <p>QE 52 CJ I - Guará II - Brasília - DF</a></p>
            </div>
          </div>
        </div>
      </div>
      <div class="formBx">
        <?php echo Form::open('sendcontact/create') ?>
          <h3>Mande uma mensagem</h3>
          <?php echo Form::text('sendcontact.nome',array('placeholder' => 'Nome')) ;
            echo Form::email('sendcontact.nome',array('placeholder' => 'E-mail')) ;
            echo Form::number('sendcontact.nome', array('placeholder' => 'Telefone'));
            echo Form::textarea('sendcontact.nome', array('placeholder' => 'Sua Mensagem'));
            echo Form::submit('Enviar'); 
            echo Form::close(); ?>
      </div>
    </div>
  </section>

  <div class="copyright">
    <p>Copyright © 2020 HOFband. Todos os direitos reservados.</p>
  </div>

  <script type="text/javascript">
    window.addEventListener('scroll', function () {
      var header = document.querySelector('nav');
      header.classList.toggle('sticky', window.scrollY > 0);
    })

    function toggleMenu() {
      var menuToggle = document.querySelector('.toggle');
      var menu = document.querySelector('.menu');
      menuToggle.classList.toggle('active');
      menu.classList.toggle('active');
    }
  </script>